version: '3.8'

services:
  spring:
    image: 'overmobile-test-v0.0.1'
    build:
      context:  .
    container_name: backend
    ports:
      - 8080:8080
    depends_on:
      - mongodb




  mongodb:
    image : mongo:5.0.8
    container_name: mongodb
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_DATABASE=overmobile
      - MONGO_REPLICA_SET_NAME=rs0
    volumes:
      - mongodb5_data:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
    command: "--replSet rs0"
volumes:
  mongodb5_data: